"""' + '
Generate Complete Inventory Management Guide Word Document' + '
This script creates a comprehensive Word document explaining the Inventory Management agent.' + '
"""' + '
from docx import Document' + '
from docx.shared import Pt, Inches, RGBColor' + '
from docx.enum.text import WD_PARAGRAPH_ALIGNMENT' + '
from docx.oxml.ns import qn' + '
from docx.oxml import OxmlElement' + '
' + '
def add_heading(doc, text, level=1):' + '
    """Add a formatted heading"""' + '
    heading = doc.add_heading(text, level=level)' + '
    heading.runs[0].font.color.rgb = RGBColor(0, 51, 102)' + '
    return heading' + '
' + '
def add_table_data(doc, headers, rows):' + '
    """Add a formatted table"""' + '
    table = doc.add_table(rows=1, cols=len(headers))' + '
    table.style = "'"Light Grid Accent 1"'"' + '
' + '
    # Header row' + '
    hdr_cells = table.rows[0].cells' + '
    for i, header in enumerate(headers):' + '
        hdr_cells[i].text = header' + '
        hdr_cells[i].paragraphs[0].runs[0].font.bold = True' + '
        hdr_cells[i].paragraphs[0].runs[0].font.color.rgb = RGBColor(255, 255, 255)' + '
        # Set background color' + '
        shading_elm = OxmlElement("'"w:shd"'")' + '
        shading_elm.set(qn("'"w:fill"'"), "'"0033AA"'")' + '
        hdr_cells[i]._element.get_or_add_tcPr().append(shading_elm)' + '
' + '
    # Data rows' + '
    for row_data in rows:' + '
        row_cells = table.add_row().cells' + '
        for i, cell_data in enumerate(row_data):' + '
            row_cells[i].text = str(cell_data)' + '
' + '
    return table' + '
' + '
def create_inventory_guide():' + '
    """Create the complete inventory management guide"""' + '
    doc = Document()' + '
' + '
    # Title' + '
    title = doc.add_heading("'"INVENTORY MANAGEMENT AGENT"'", level=0)' + '
    title.alignment = WD_PARAGRAPH_ALIGNMENT.CENTER' + '
    title.runs[0].font.color.rgb = RGBColor(0, 51, 102)' + '
    title.runs[0].font.size = Pt(24)' + '
' + '
    subtitle = doc.add_paragraph("'"Complete Technical Reference Guide"'")' + '
    subtitle.alignment = WD_PARAGRAPH_ALIGNMENT.CENTER' + '
    subtitle.runs[0].italic = True' + '
' + '
    doc.add_paragraph("'"AMIS - Autonomous Manufacturing Intelligence System"'")' + '
    doc.add_paragraph("'"100% Database-Driven | Real-Time Data | SQL Validation"'")' + '
    doc.add_paragraph()' + '
' + '
    # ===================================================================' + '
    # SECTION 1: OVERVIEW' + '
    # ===================================================================' + '
    add_heading(doc, "'"1. OVERVIEW"'", level=1)' + '
' + '
    doc.add_paragraph(' + '
        "'"The Inventory Management Agent is an AI-powered intelligent system that analyzes inventory "'"' + '
        "'"levels, calculates optimal reorder points, evaluates stockout risks, and generates replenishment "'"' + '
        "'"plans. It uses advanced algorithms including Reorder Point (ROP), Economic Order Quantity (EOQ), "'"' + '
        "'"Monte Carlo simulation, and multi-supplier allocation strategies."'"' + '
    )' + '
' + '
    doc.add_paragraph("'"Key Capabilities:"'")' + '
    capabilities = [' + '
        "'"Real-time inventory status monitoring with warehouse zone analysis"'",' + '
        "'"Reorder Point (ROP) calculation with demand & lead time variability"'",' + '
        "'"Safety stock optimization across multiple service levels (85%-99%)"'",' + '
        "'"Monte Carlo stockout risk simulation (1,000 runs)"'",' + '
        "'"Economic Order Quantity (EOQ) and holding cost analysis"'",' + '
        "'"Multi-week replenishment planning with supplier allocation"'",' + '
    ]' + '
    for cap in capabilities:' + '
        p = doc.add_paragraph(cap, style="'"List Bullet"'")' + '
' + '
    # ===================================================================' + '
    # SECTION 2: DATABASE TABLES USED' + '
    # ===================================================================' + '
    doc.add_page_break()' + '
    add_heading(doc, "'"2. DATABASE TABLES USED"'", level=1)' + '
' + '
    doc.add_paragraph(' + '
        "'"The Inventory Management Agent queries data from 12 database tables. All data is persistent "'"' + '
        "'"and can be validated via SQL queries."'"' + '
    )' + '
' + '
    table_data = [' + '
        ["'"Table Name"'", "'"Records"'", "'"Purpose"'", "'"Key Columns"'"],' + '
        ["'"inventory"'", "'"1"'", "'"Current stock levels"'", "'"product_id, current_stock, safety_stock, avg_daily_usage, lead_time, unit_cost, holding_cost"'"],' + '
        ["'"products"'", "'"1"'", "'"Product details"'", "'"id, name, category, status"'"],' + '
        ["'"warehouse_zones"'", "'"3"'", "'"Warehouse zone allocation"'", "'"zone_id, product_id, capacity, current_units, utilization, zone_type"'"],' + '
        ["'"stockout_events"'", "'"3"'", "'"Historical stockout tracking"'", "'"product_id, event_date, duration_days, units_short, revenue_lost, customers_affected"'"],' + '
        ["'"purchase_orders"'", "'"12"'", "'"PO history & open orders"'", "'"po_id, product_id, supplier_id, quantity, order_date, expected_delivery_date, status"'"],' + '
        ["'"suppliers"'", "'"2"'", "'"Supplier information"'", "'"id, name, lead_time, lead_time_variability, on_time_delivery, quality_score, base_cost, moq"'"],' + '
        ["'"supplier_contracts"'", "'"2"'", "'"Active contracts"'", "'"id, supplier_id, start_date, end_date, volume, status"'"],' + '
        ["'"supplier_risk"'", "'"6"'", "'"Supply chain risk"'", "'"component_id, sourcing_type, qualified_suppliers, risk_score, mitigation_strategy"'"],' + '
        ["'"bom_items"'", "'"6"'", "'"Bill of materials"'", "'"product_id, component_id, quantity, stock, supplier_id, cost"'"],' + '
        ["'"historical_demand_data"'", "'"156"'", "'"Historical demand"'", "'"product_id, week_start_date, demand_units, promotions_active"'"],' + '
        ["'"market_context_data"'", "'"1"'", "'"Market conditions"'", "'"industry_growth_rate, economic_indicator, competitor_activity"'"],' + '
        ["'"production_lines"'", "'"5"'", "'"Production capacity"'", "'"id, status, capacity_per_hour, efficiency"'"],' + '
    ]' + '
' + '
    add_table_data(doc, table_data[0], table_data[1:])' + '
' + '
    doc.add_paragraph()' + '
    doc.add_paragraph("'"SQL Validation Example:"'").bold = True' + '
    code = doc.add_paragraph(' + '
        "SELECT * FROM inventory WHERE product_id = "'"PROD-A"'";\n"' + '
        "SELECT * FROM warehouse_zones WHERE product_id = "'"PROD-A"'";\n"' + '
        "SELECT * FROM purchase_orders WHERE status IN ("'"open"'", "'"in_transit"'");"' + '
    )' + '
    code.runs[0].font.name = "'"Courier New"'"' + '
    code.runs[0].font.size = Pt(9)' + '
' + '
    # ===================================================================' + '
    # SECTION 3: TOOL #1 - GET INVENTORY STATUS' + '
    # ===================================================================' + '
    doc.add_page_break()' + '
    add_heading(doc, "'"3. TOOL #1: get_inventory_status()"'", level=1)' + '
' + '
    doc.add_paragraph(' + '
        "'"Purpose: Get a complete 360° view of inventory status including current stock, warehouse zones, "'"' + '
        "'"supplier performance, stockout history, and health indicators."'"' + '
    )' + '
' + '
    add_heading(doc, "'"3.1 Input Parameters"'", level=2)' + '
    params = [' + '
        ["'"Parameter"'", "'"Type"'", "'"Default"'", "'"Description"'"],' + '
        ["'"product_id"'", "'"str"'", "'"PROD-A"'", "'"Product ID to check inventory for"'"],' + '
    ]' + '
    add_table_data(doc, params[0], params[1:])' + '
' + '
    add_heading(doc, "'"3.2 Data Sources"'", level=2)' + '
    doc.add_paragraph("'"This tool calls 6 database query functions:"'")' + '
    sources = [' + '
        "'"get_current_inventory() → queries inventory table"'",' + '
        "'"get_warehouse_details() → queries warehouse_zones table"'",' + '
        "'"get_supplier_performance() → queries suppliers, purchase_orders tables"'",' + '
        "'"get_historical_stockouts() → queries stockout_events table"'",' + '
        "'"get_product_info() → queries products, inventory tables"'",' + '
        "'"get_reorder_history() → queries purchase_orders table"'",' + '
    ]' + '
    for source in sources:' + '
        p = doc.add_paragraph(source, style="'"List Bullet"'")' + '
        p.runs[0].font.name = "'"Courier New"'"' + '
' + '
    add_heading(doc, "'"3.3 Health Indicators Calculated"'", level=2)' + '
    indicators = [' + '
        ["'"Indicator"'", "'"Formula"'", "'"Example Value"'"],' + '
        ["'"days_of_supply"'", "'"current_stock / avg_daily_consumption"'", "'"13.0 days"'"],' + '
        ["'"above_safety_stock"'", "'"current_stock > safety_stock"'", "'"True"'"],' + '
        ["'"buffer_above_safety"'", "'"current_stock - safety_stock"'", "'"1,550 units"'"],' + '
        ["'"incoming_pipeline_units"'", "'"SUM(incoming orders quantity)"'", "'"2,300 units"'"],' + '
        ["'"effective_days_of_supply"'", "'"(current + incoming) / avg_daily"'", "'"29.2 days"'"],' + '
        ["'"warehouse_utilization_pct"'", "'"(total_units / capacity) × 100"'", "'"37.0%"'"],' + '
        ["'"stockout_events_last_12_months"'", "'"COUNT(stockout events)"'", "'"3 events"'"],' + '
        ["'"total_stockout_revenue_lost"'", "'"SUM(revenue_lost)"'", "'"$111,875"'"],' + '
    ]' + '
    add_table_data(doc, indicators[0], indicators[1:])' + '
' + '
    add_heading(doc, "'"3.4 SQL Query Example"'", level=2)' + '
    sql = doc.add_paragraph(' + '
        "'"SELECT i.product_id, i.current_stock, i.safety_stock, i.avg_daily_usage,\\n"'"' + '
        "'"       w.total_capacity, w.total_units, w.utilization_pct\\n"'"' + '
        "'"FROM inventory i\\n"'"' + '
        "'"JOIN (SELECT product_id, SUM(capacity) as total_capacity,\\n"'"' + '
        "'"             SUM(current_units) as total_units,\\n"'"' + '
        "'"             ROUND((SUM(current_units) * 100.0 / SUM(capacity)), 1) as utilization_pct\\n"'"' + '
        "'"      FROM warehouse_zones GROUP BY product_id) w\\n"'"' + '
        "'"ON i.product_id = w.product_id\\n"'"' + '
        "'"WHERE i.product_id = \\"'"PROD-A\\"'";"'"' + '
    )' + '
    sql.runs[0].font.name = "'"Courier New"'"' + '
    sql.runs[0].font.size = Pt(9)' + '
' + '
    add_heading(doc, "'"3.5 Example Output"'", level=2)' + '
    doc.add_paragraph("'"Current Stock: 1,850 units"'")' + '
    doc.add_paragraph("'"Safety Stock: 300 units"'")' + '
    doc.add_paragraph("'"Days of Supply: 13.0 days"'")' + '
    doc.add_paragraph("'"Warehouse Utilization: 37.0%"'")' + '
    doc.add_paragraph("'"Incoming Pipeline: 2,300 units (ETA: 4-7 days)"'")' + '
    doc.add_paragraph("'"Recent Stockouts: 3 events, $111,875 revenue lost"'")' + '
' + '
    # ===================================================================' + '
    # SECTION 4: TOOL #2 - CALCULATE REORDER POINT' + '
    # ===================================================================' + '
    doc.add_page_break()' + '
    add_heading(doc, "'"4. TOOL #2: calculate_reorder_point()"'", level=1)' + '
' + '
    doc.add_paragraph(' + '
        "'"Purpose: Calculate the Reorder Point (ROP) using the standard inventory management formula "'"' + '
        "'"that accounts for both demand variability and lead time variability. This determines WHEN to "'"' + '
        "'"place the next order."'"' + '
    )' + '
' + '
    add_heading(doc, "'"4.1 Formula"'", level=2)' + '
    doc.add_paragraph("'"ROP = (Average Daily Demand × Lead Time) + Safety Stock"'").bold = True' + '
    doc.add_paragraph()' + '
    doc.add_paragraph("'"Safety Stock Formula:"'").bold = True' + '
    doc.add_paragraph("'"SS = Z × √(LT × σ_demand² + demand² × σ_LT²)"'")' + '
    doc.add_paragraph()' + '
    doc.add_paragraph("'"Where:"'")' + '
    vars_list = [' + '
        "'"Z = Z-score for target service level (e.g., 1.645 for 95%)"'",' + '
        "'"LT = Average lead time in days"'",' + '
        "'"σ_demand = Standard deviation of daily demand"'",' + '
        "'"demand = Average daily demand"'",' + '
        "'"σ_LT = Standard deviation of lead time"'",' + '
    ]' + '
    for var in vars_list:' + '
        doc.add_paragraph(var, style="'"List Bullet"'")' + '
' + '
    add_heading(doc, "'"4.2 Input Parameters"'", level=2)' + '
    rop_params = [' + '
        ["'"Parameter"'", "'"Type"'", "'"Default"'", "'"Description"'"],' + '
        ["'"product_id"'", "'"str"'", "'"PROD-A"'", "'"Product ID"'"],' + '
        ["'"expected_daily_demand"'", "'"float"'", "'"142.0"'", "'"Average daily demand (from forecast)"'"],' + '
        ["'"demand_std_dev_daily"'", "'"float"'", "'"25.0"'", "'"Daily demand standard deviation"'"],' + '
        ["'"lead_time_days"'", "'"float"'", "'"5.0"'", "'"Average supplier lead time"'"],' + '
        ["'"lead_time_std_dev_days"'", "'"float"'", "'"1.0"'", "'"Lead time standard deviation"'"],' + '
        ["'"service_level_pct"'", "'"float"'", "'"95.0"'", "'"Target service level (85-99%)"'"],' + '
    ]' + '
    add_table_data(doc, rop_params[0], rop_params[1:])' + '
' + '
    add_heading(doc, "'"4.3 Z-Score Lookup Table"'", level=2)' + '
    z_scores = [' + '
        ["'"Service Level"'", "'"Z-Score"'", "'"Meaning"'"],' + '
        ["'"85%"'", "'"1.04"'", "'"Basic service"'"],' + '
        ["'"90%"'", "'"1.28"'", "'"Good service"'"],' + '
        ["'"95%"'", "'"1.645"'", "'"Industry standard"'"],' + '
        ["'"97%"'", "'"1.88"'", "'"High service"'"],' + '
        ["'"99%"'", "'"2.326"'", "'"Premium service"'"],' + '
    ]' + '
    add_table_data(doc, z_scores[0], z_scores[1:])' + '
' + '
    add_heading(doc, "'"4.4 Step-by-Step Calculation Example"'", level=2)' + '
    doc.add_paragraph("'"Given:"'")' + '
    doc.add_paragraph("'"• Daily demand = 142 units, σ_demand = 25 units"'")' + '
    doc.add_paragraph("'"• Lead time = 5 days, σ_LT = 1 day"'")' + '
    doc.add_paragraph("'"• Service level = 95% → Z = 1.645"'")' + '
    doc.add_paragraph()' + '
    doc.add_paragraph("'"Step 1: Calculate Safety Stock"'").bold = True' + '
    doc.add_paragraph("'"SS = 1.645 × √(5 × 25² + 142² × 1²)"'")' + '
    doc.add_paragraph("'"SS = 1.645 × √(5 × 625 + 20,164 × 1)"'")' + '
    doc.add_paragraph("'"SS = 1.645 × √(3,125 + 20,164)"'")' + '
    doc.add_paragraph("'"SS = 1.645 × √23,289"'")' + '
    doc.add_paragraph("'"SS = 1.645 × 152.6 = 251 units"'")' + '
    doc.add_paragraph()' + '
    doc.add_paragraph("'"Step 2: Calculate Avg Demand During Lead Time"'").bold = True' + '
    doc.add_paragraph("'"Avg = 142 units/day × 5 days = 710 units"'")' + '
    doc.add_paragraph()' + '
    doc.add_paragraph("'"Step 3: Calculate ROP"'").bold = True' + '
    doc.add_paragraph("'"ROP = 710 + 251 = 961 units"'")' + '
    doc.add_paragraph()' + '
    doc.add_paragraph("'"Result: Order when stock drops below 961 units"'").bold = True' + '
' + '
    add_heading(doc, "'"4.5 SQL Query to Verify"'", level=2)' + '
    rop_sql = doc.add_paragraph(' + '
        "'"SELECT i.current_stock, i.safety_stock, i.avg_daily_usage, i.lead_time,\\n"'"' + '
        "'"       (i.avg_daily_usage * i.lead_time + i.safety_stock) as calculated_rop,\\n"'"' + '
        "'"       CASE WHEN i.current_stock < (i.avg_daily_usage * i.lead_time + i.safety_stock)\\n"'"' + '
        "'"            THEN \\"'"REORDER NOW\\"'"\\n"'"' + '
        "'"            ELSE \\"'"Stock OK\\"'"\\n"'"' + '
        "'"       END as reorder_status\\n"'"' + '
        "'"FROM inventory i\\n"'"' + '
        "'"WHERE i.product_id = \\"'"PROD-A\\"'";"'"' + '
    )' + '
    rop_sql.runs[0].font.name = "'"Courier New"'"' + '
    rop_sql.runs[0].font.size = Pt(9)' + '
' + '
    # ===================================================================' + '
    # SECTION 5: TOOL #3 - OPTIMIZE SAFETY STOCK' + '
    # ===================================================================' + '
    doc.add_page_break()' + '
    add_heading(doc, "'"5. TOOL #3: optimize_safety_stock()"'", level=1)' + '
' + '
    doc.add_paragraph(' + '
        "'"Purpose: Find the optimal safety stock level by evaluating multiple service levels (85% to 99%). "'"' + '
        "'"For each level, calculates total cost (holding cost + expected stockout cost) and finds the minimum."'"' + '
    )' + '
' + '
    add_heading(doc, "'"5.1 Cost Trade-off Analysis"'", level=2)' + '
    doc.add_paragraph("'"Total Cost = Holding Cost + Expected Stockout Cost"'")' + '
    doc.add_paragraph()' + '
    doc.add_paragraph("'"Holding Cost = Safety Stock × Annual Holding Cost per Unit"'")' + '
    doc.add_paragraph("'"Stockout Cost = Stockout Probability × Expected Shortage × Stockout Cost per Unit"'")' + '
' + '
    add_heading(doc, "'"5.2 Input Parameters"'", level=2)' + '
    opt_params = [' + '
        ["'"Parameter"'", "'"Type"'", "'"Default"'", "'"Description"'"],' + '
        ["'"product_id"'", "'"str"'", "'"PROD-A"'", "'"Product ID"'"],' + '
        ["'"expected_daily_demand"'", "'"float"'", "'"142.0"'", "'"Average daily demand"'"],' + '
        ["'"demand_std_dev_daily"'", "'"float"'", "'"25.0"'", "'"Demand standard deviation"'"],' + '
        ["'"lead_time_days"'", "'"float"'", "'"5.0"'", "'"Average lead time"'"],' + '
        ["'"lead_time_std_dev_days"'", "'"float"'", "'"1.0"'", "'"Lead time std dev"'"],' + '
        ["'"holding_cost_per_unit_per_year"'", "'"float"'", "'"2.30"'", "'"Annual holding cost"'"],' + '
        ["'"stockout_cost_per_unit"'", "'"float"'", "'"45.00"'", "'"Cost per unit short"'"],' + '
    ]' + '
    add_table_data(doc, opt_params[0], opt_params[1:])' + '
' + '
    add_heading(doc, "'"5.3 Analysis Results Example"'", level=2)' + '
    analysis = [' + '
        ["'"Service Level"'", "'"Safety Stock"'", "'"Holding Cost/Year"'", "'"Stockout Cost/Year"'", "'"Total Cost"'"],' + '
        ["'"85%"'", "'"159 units"'", "'"$366"'", "'"$4,250"'", "'"$4,616"'"],' + '
        ["'"90%"'", "'"195 units"'", "'"$449"'", "'"$3,120"'", "'"$3,569"'"],' + '
        ["'"95%"'", "'"251 units"'", "'"$577"'", "'"$1,950"'", "'"$2,527"'"],' + '
        ["'"97%"'", "'"287 units"'", "'"$660"'", "'"$1,280"'", "'"$1,940"'"],' + '
        ["'"99%"'", "'"355 units"'", "'"$817"'", "'"$520"'", "'"$1,337 ← OPTIMAL"'"],' + '
    ]' + '
    add_table_data(doc, analysis[0], analysis[1:])' + '
' + '
    doc.add_paragraph()' + '
    doc.add_paragraph("'"Recommendation: Set safety stock to 355 units (99% service level) to minimize total cost at $1,337/year."'")' + '
    doc.add_paragraph()' + '
    doc.add_paragraph("'"Current Safety Stock: 300 units (~95% service level)"'")' + '
    doc.add_paragraph("'"Potential Annual Savings: $1,190 by increasing to optimal level"'")' + '
' + '
    add_heading(doc, "'"5.4 SQL Query Example"'", level=2)' + '
    opt_sql = doc.add_paragraph(' + '
        "'"SELECT i.safety_stock as current_safety_stock,\\n"'"' + '
        "'"       i.holding_cost,\\n"'"' + '
        "'"       (i.safety_stock * i.holding_cost) as annual_holding_cost,\\n"'"' + '
        "'"       s.revenue_lost / s.duration_days as avg_daily_stockout_cost\\n"'"' + '
        "'"FROM inventory i\\n"'"' + '
        "'"LEFT JOIN stockout_events s ON i.product_id = s.product_id\\n"'"' + '
        "'"WHERE i.product_id = \\"'"PROD-A\\"'";"'"' + '
    )' + '
    opt_sql.runs[0].font.name = "'"Courier New"'"' + '
    opt_sql.runs[0].font.size = Pt(9)' + '
' + '
    # ===================================================================' + '
    # SECTION 6: TOOL #4 - SIMULATE STOCKOUT RISK' + '
    # ===================================================================' + '
    doc.add_page_break()' + '
    add_heading(doc, "'"6. TOOL #4: simulate_stockout_risk()"'", level=1)' + '
' + '
    doc.add_paragraph(' + '
        "'"Purpose: Run Monte Carlo simulation to quantify stockout probability over a 14-day horizon. "'"' + '
        "'"Simulates 1,000 scenarios of daily demand variation and tracks when stock hits zero."'"' + '
    )' + '
' + '
    add_heading(doc, "'"6.1 Monte Carlo Simulation"'", level=2)' + '
    doc.add_paragraph("'"Algorithm:"'")' + '
    algo = [' + '
        "'"1. Start with current stock (e.g., 1,850 units)"'",' + '
        "'"2. FOR each of 1,000 simulations:"'",' + '
        "'"   a. FOR each day (1 to 14):"'",' + '
        "'"      - Draw random daily demand from Normal(142, 25)"'",' + '
        "'"      - Subtract demand from stock"'",' + '
        "'"      - Check if incoming orders arrive (with ±1 day jitter)"'",' + '
        "'"      - Track if stock <= 0"'",' + '
        "'"3. Calculate % of simulations that hit stockout"'",' + '
        "'"4. Create daily risk profile"'",' + '
    ]' + '
    for step in algo:' + '
        doc.add_paragraph(step, style="'"List Number"'")' + '
' + '
    add_heading(doc, "'"6.2 Input Parameters"'", level=2)' + '
    sim_params = [' + '
        ["'"Parameter"'", "'"Type"'", "'"Default"'", "'"Description"'"],' + '
        ["'"product_id"'", "'"str"'", "'"PROD-A"'", "'"Product to simulate"'"],' + '
        ["'"current_stock"'", "'"int"'", "'"1850"'", "'"Current units on hand"'"],' + '
        ["'"expected_daily_demand"'", "'"float"'", "'"142.0"'", "'"Average daily demand"'"],' + '
        ["'"demand_std_dev_daily"'", "'"float"'", "'"25.0"'", "'"Demand variability"'"],' + '
        ["'"horizon_days"'", "'"int"'", "'"14"'", "'"Days to simulate forward"'"],' + '
        ["'"simulations"'", "'"int"'", "'"1000"'", "'"Number of Monte Carlo runs"'"],' + '
    ]' + '
    add_table_data(doc, sim_params[0], sim_params[1:])' + '
' + '
    add_heading(doc, "'"6.3 Example Results"'", level=2)' + '
    doc.add_paragraph("'"Overall Stockout Probability: 2.3% (23 out of 1,000 simulations)"'")' + '
    doc.add_paragraph()' + '
    doc.add_paragraph("'"Daily Risk Profile:"'")' + '
    risk_profile = [' + '
        ["'"Day"'", "'"Avg Stock"'", "'"Min Stock"'", "'"Max Stock"'", "'"Stockout Prob"'"],' + '
        ["'"Day 1"'", "'"1,708"'", "'"1,612"'", "'"1,805"'", "'"0.0%"'"],' + '
        ["'"Day 2"'", "'"1,566"'", "'"1,398"'", "'"1,733"'", "'"0.0%"'"],' + '
        ["'"Day 3"'", "'"1,424"'", "'"1,184"'", "'"1,661"'", "'"0.1%"'"],' + '
        ["'"Day 4"'", "'"2,682"'", "'"2,340"'", "'"3,024"'", "'"0.0%  ← Orders arrive"'"],' + '
        ["'"Day 5"'", "'"2,540"'", "'"2,198"'", "'"2,882"'", "'"0.0%"'"],' + '
        ["'"Day 7"'", "'"2,256"'", "'"1,914"'", "'"2,598"'", "'"0.0%"'"],' + '
        ["'"Day 10"'", "'"1,830"'", "'"1,346"'", "'"2,314"'", "'"0.3%"'"],' + '
        ["'"Day 14"'", "'"1,262"'", "'"636"'", "'"1,888"'", "'"2.3%  ← Critical"'"],' + '
    ]' + '
    add_table_data(doc, risk_profile[0], risk_profile[1:])' + '
' + '
    doc.add_paragraph()' + '
    doc.add_paragraph("'"Worst Case Scenario:"'")' + '
    doc.add_paragraph("'"• Minimum stock reached: 636 units on Day 14"'")' + '
    doc.add_paragraph("'"• No stockout in worst case (stock stays positive)"'")' + '
    doc.add_paragraph("'"• Recommendation: Current stock level is adequate for 14-day horizon"'")' + '
' + '
    add_heading(doc, "'"6.4 SQL Query for Historical Validation"'", level=2)' + '
    sim_sql = doc.add_paragraph(' + '
        "'"SELECT s.product_id, s.event_date,\\n"'"' + '
        "'"       s.duration_days, s.units_short, s.root_cause,\\n"'"' + '
        "'"       i.current_stock, i.safety_stock,\\n"'"' + '
        "'"       (i.current_stock - i.safety_stock) as buffer\\n"'"' + '
        "'"FROM stockout_events s\\n"'"' + '
        "'"JOIN inventory i ON s.product_id = i.product_id\\n"'"' + '
        "'"WHERE s.product_id = \\"'"PROD-A\\"'"\\n"'"' + '
        "'"ORDER BY s.event_date DESC;"'"' + '
    )' + '
    sim_sql.runs[0].font.name = "'"Courier New"'"' + '
    sim_sql.runs[0].font.size = Pt(9)' + '
' + '
    # ===================================================================' + '
    # SECTION 7: TOOL #5 - EVALUATE HOLDING COSTS' + '
    # ===================================================================' + '
    doc.add_page_break()' + '
    add_heading(doc, "'"7. TOOL #5: evaluate_holding_costs()"'", level=1)' + '
' + '
    doc.add_paragraph(' + '
        "'"Purpose: Analyze the economic trade-off between carrying costs and stockout risk. "'"' + '
        "'"Includes Economic Order Quantity (EOQ) calculation to find the optimal order size."'"' + '
    )' + '
' + '
    add_heading(doc, "'"7.1 EOQ Formula"'", level=2)' + '
    doc.add_paragraph("'"EOQ = √(2 × Annual Demand × Ordering Cost / Holding Cost per Unit)"'").bold = True' + '
    doc.add_paragraph()' + '
    doc.add_paragraph("'"Example Calculation:"'")' + '
    doc.add_paragraph("'"• Annual Demand = 142 units/day × 365 = 51,830 units"'")' + '
    doc.add_paragraph("'"• Ordering Cost = $150 per order"'")' + '
    doc.add_paragraph("'"• Holding Cost = $2.30 per unit per year"'")' + '
    doc.add_paragraph()' + '
    doc.add_paragraph("'"EOQ = √(2 × 51,830 × 150 / 2.30)"'")' + '
    doc.add_paragraph("'"EOQ = √(15,549,000 / 2.30)"'")' + '
    doc.add_paragraph("'"EOQ = √6,760,435"'")' + '
    doc.add_paragraph("'"EOQ = 2,600 units"'")' + '
    doc.add_paragraph()' + '
    doc.add_paragraph("'"Reorder Frequency: 2,600 / 142 = 18.3 days (approximately every 2.5 weeks)"'")' + '
' + '
    add_heading(doc, "'"7.2 Input Parameters"'", level=2)' + '
    eoq_params = [' + '
        ["'"Parameter"'", "'"Type"'", "'"Default"'", "'"Description"'"],' + '
        ["'"product_id"'", "'"str"'", "'"PROD-A"'", "'"Product ID"'"],' + '
        ["'"current_stock"'", "'"int"'", "'"1850"'", "'"Current inventory"'"],' + '
        ["'"safety_stock"'", "'"int"'", "'"300"'", "'"Safety stock setting"'"],' + '
        ["'"holding_cost_per_unit_per_year"'", "'"float"'", "'"2.30"'", "'"Annual holding cost"'"],' + '
        ["'"stockout_cost_per_unit"'", "'"float"'", "'"45.00"'", "'"Stockout penalty"'"],' + '
        ["'"avg_daily_demand"'", "'"float"'", "'"142.0"'", "'"Daily demand"'"],' + '
        ["'"warehouse_capacity"'", "'"int"'", "'"5000"'", "'"Max warehouse capacity"'"],' + '
    ]' + '
    add_table_data(doc, eoq_params[0], eoq_params[1:])' + '
' + '
    add_heading(doc, "'"7.3 Cost Comparison at Different Stock Levels"'", level=2)' + '
    cost_comp = [' + '
        ["'"Stock Level"'", "'"Days Supply"'", "'"Daily Hold Cost"'", "'"Annual Hold Cost"'", "'"Stockout Risk"'"],' + '
        ["'"300 units"'", "'"2.1 days"'", "'"$1.89"'", "'"$690"'", "'"78.5%"'"],' + '
        ["'"994 units"'", "'"7.0 days"'", "'"$6.29"'", "'"$2,296"'", "'"12.0%"'"],' + '
        ["'"1,350 units"'", "'"9.5 days"'", "'"$8.54"'", "'"$3,120"'", "'"4.5%"'"],' + '
        ["'"1,850 units"'", "'"13.0 days"'", "'"$11.70"'", "'"$4,275"'", "'"1.2%  ← Current"'"],' + '
        ["'"2,350 units"'", "'"16.5 days"'", "'"$14.86"'", "'"$5,430"'", "'"0.5%"'"],' + '
    ]' + '
    add_table_data(doc, cost_comp[0], cost_comp[1:])' + '
' + '
    doc.add_paragraph()' + '
    doc.add_paragraph("'"Current Position Analysis:"'")' + '
    doc.add_paragraph("'"• Stock: 1,850 units (above safety stock by 1,550 units)"'")' + '
    doc.add_paragraph("'"• Daily Holding Cost: $11.70"'")' + '
    doc.add_paragraph("'"• Annual Holding Cost: $4,275"'")' + '
    doc.add_paragraph("'"• Days of Supply: 13.0 days"'")' + '
    doc.add_paragraph("'"• Capital Tied Up: 1,850 × $52 = $96,200"'")' + '
' + '
    add_heading(doc, "'"7.4 Historical Stockout Impact"'", level=2)' + '
    doc.add_paragraph("'"Events Last 12 Months: 3 stockout events"'")' + '
    doc.add_paragraph("'"Total Revenue Lost: $111,875"'")' + '
    doc.add_paragraph("'"Average Cost per Event: $37,292"'")' + '
    doc.add_paragraph("'"Average Duration: 3.0 days per event"'")' + '
' + '
    add_heading(doc, "'"7.5 SQL Query Example"'", level=2)' + '
    eoq_sql = doc.add_paragraph(' + '
        "'"SELECT i.current_stock, i.unit_cost, i.holding_cost,\\n"'"' + '
        "'"       (i.current_stock * i.unit_cost) as capital_tied_up,\\n"'"' + '
        "'"       (i.current_stock * i.holding_cost) as annual_holding_cost,\\n"'"' + '
        "'"       COUNT(s.id) as stockout_events,\\n"'"' + '
        "'"       SUM(s.revenue_lost) as total_revenue_lost\\n"'"' + '
        "'"FROM inventory i\\n"'"' + '
        "'"LEFT JOIN stockout_events s ON i.product_id = s.product_id\\n"'"' + '
        "'"     AND s.event_date >= date(\\"'"now\\"'", \\"'"-12 months\\"'")\\n"'"' + '
        "'"WHERE i.product_id = \\"'"PROD-A\\"'"\\n"'"' + '
        "'"GROUP BY i.product_id;"'"' + '
    )' + '
    eoq_sql.runs[0].font.name = "'"Courier New"'"' + '
    eoq_sql.runs[0].font.size = Pt(9)' + '
' + '
    # ===================================================================' + '
    # SECTION 8: TOOL #6 - GENERATE REPLENISHMENT PLAN' + '
    # ===================================================================' + '
    doc.add_page_break()' + '
    add_heading(doc, "'"8. TOOL #6: generate_replenishment_plan()"'", level=1)' + '
' + '
    doc.add_paragraph(' + '
        "'"Purpose: Generate a week-by-week replenishment schedule for the next 4 weeks. "'"' + '
        "'"Determines when to order, how much to order, and splits orders across suppliers "'"' + '
        "'"based on reliability (65% Supplier A, 35% Supplier B)."'"' + '
    )' + '
' + '
    add_heading(doc, "'"8.1 Multi-Supplier Allocation Strategy"'", level=2)' + '
    doc.add_paragraph("'"Supplier A (65% of orders):"'")' + '
    doc.add_paragraph("'"• Higher reliability: 92.5% on-time delivery"'")' + '
    doc.add_paragraph("'"• Faster lead time: 4.2 days (±0.8 days)"'")' + '
    doc.add_paragraph("'"• Quality: 98.8% (1.2% reject rate)"'")' + '
    doc.add_paragraph("'"• Cost: $52.00 per unit"'")' + '
    doc.add_paragraph()' + '
    doc.add_paragraph("'"Supplier B (35% of orders):"'")' + '
    doc.add_paragraph("'"• Lower cost: $49.50 per unit (saves $2.50/unit = 5% savings)"'")' + '
    doc.add_paragraph("'"• Longer lead time: 6.8 days (±1.5 days)"'")' + '
    doc.add_paragraph("'"• On-time delivery: 85.0%"'")' + '
    doc.add_paragraph("'"• Diversification benefit: reduces single-supplier risk"'")' + '
' + '
    add_heading(doc, "'"8.2 Input Parameters"'", level=2)' + '
    plan_params = [' + '
        ["'"Parameter"'", "'"Type"'", "'"Default"'", "'"Description"'"],' + '
        ["'"product_id"'", "'"str"'", "'"PROD-A"'", "'"Product to plan for"'"],' + '
        ["'"expected_weekly_demand"'", "'"float"'", "'"1050.0"'", "'"Weekly demand from forecast"'"],' + '
        ["'"demand_std_dev_weekly"'", "'"float"'", "'"120.0"'", "'"Weekly demand uncertainty"'"],' + '
        ["'"planning_horizon_weeks"'", "'"int"'", "'"4"'", "'"Number of weeks to plan"'"],' + '
        ["'"target_service_level_pct"'", "'"float"'", "'"95.0"'", "'"Service level target"'"],' + '
        ["'"current_stock"'", "'"int"'", "'"1850"'", "'"Starting inventory"'"],' + '
    ]' + '
    add_table_data(doc, plan_params[0], plan_params[1:])' + '
' + '
    add_heading(doc, "'"8.3 Week-by-Week Plan Example"'", level=2)' + '
    plan_example = [' + '
        ["'"Week"'", "'"Start Stock"'", "'"Incoming"'", "'"Demand"'", "'"End Stock"'", "'"Order?"'", "'"Order Details"'"],' + '
        ["'"Week 1"'", "'"1,850"'", "'"2,300"'", "'"1,050"'", "'"3,100"'", "'"No"'", "'"Stock adequate"'"],' + '
        ["'"Week 2"'", "'"3,100"'", "'"0"'", "'"1,050"'", "'"2,050"'", "'"No"'", "'"Above safety stock"'"],' + '
        ["'"Week 3"'", "'"2,050"'", "'"0"'", "'"1,050"'", "'"1,000"'", "'"Yes"'", "'"SUP-A: 1,300 units ($67,600)\\nSUP-B: 700 units ($34,650)"'"],' + '
        ["'"Week 4"'", "'"1,000"'", "'"1,300"'", "'"1,050"'", "'"1,250"'", "'"Yes"'", "'"SUP-A: 1,300 units ($67,600)\\nSUP-B: 700 units ($34,650)"'"],' + '
    ]' + '
    add_table_data(doc, plan_example[0], plan_example[1:])' + '
' + '
    doc.add_paragraph()' + '
    doc.add_paragraph("'"Plan Summary:"'")' + '
    doc.add_paragraph("'"• Total Units Ordered: 4,000 units"'")' + '
    doc.add_paragraph("'"• Total Procurement Cost: $204,500"'")' + '
    doc.add_paragraph("'"• Average Projected Stock: 1,850 units"'")' + '
    doc.add_paragraph("'"• Min Projected Stock: 1,000 units (above safety stock)"'")' + '
    doc.add_paragraph("'"• Weeks Below Safety Stock: 0 weeks"'")' + '
' + '
    add_heading(doc, "'"8.4 Order Trigger Logic"'", level=2)' + '
    doc.add_paragraph("'"Order is placed when:"'")' + '
    doc.add_paragraph("'"Projected Stock Next Week < (Target Safety Stock × 1.5)"'")' + '
    doc.add_paragraph()' + '
    doc.add_paragraph("'"Target Stock After Order:"'")' + '
    doc.add_paragraph("'"Target = (Expected Weekly Demand × 2) + Target Safety Stock"'")' + '
    doc.add_paragraph()' + '
    doc.add_paragraph("'"Order Quantity:"'")' + '
    doc.add_paragraph("'"Qty = Target Stock - Current Stock"'")' + '
' + '
    add_heading(doc, "'"8.5 SQL Query for Replenishment Tracking"'", level=2)' + '
    plan_sql = doc.add_paragraph(' + '
        "'"SELECT po.order_date, po.supplier_id,\\n"'"' + '
        "'"       po.quantity, po.unit_cost, po.total_cost,\\n"'"' + '
        "'"       po.expected_delivery_date, po.status,\\n"'"' + '
        "'"       s.on_time_delivery, s.lead_time\\n"'"' + '
        "'"FROM purchase_orders po\\n"'"' + '
        "'"JOIN suppliers s ON po.supplier_id = s.id\\n"'"' + '
        "'"WHERE po.product_id = \\"'"PROD-A\\"'"\\n"'"' + '
        "'"  AND po.status IN (\\"'"open\\"'", \\"'"in_transit\\"'", \\"'"processing\\"'")\\n"'"' + '
        "'"ORDER BY po.expected_delivery_date;"'"' + '
    )' + '
    plan_sql.runs[0].font.name = "'"Courier New"'"' + '
    plan_sql.runs[0].font.size = Pt(9)' + '
' + '
    # ===================================================================' + '
    # SECTION 9: COMPLETE EXECUTION FLOW' + '
    # ===================================================================' + '
    doc.add_page_break()' + '
    add_heading(doc, "'"9. COMPLETE EXECUTION FLOW"'", level=1)' + '
' + '
    doc.add_paragraph(' + '
        "'"When the Inventory Management Agent is invoked by the user, it follows this decision flow:"'"' + '
    )' + '
' + '
    flow = [' + '
        "'"1. Call get_inventory_status() to understand current situation"'",' + '
        "'"   → Queries: inventory, warehouse_zones, suppliers, stockout_events, purchase_orders"'",' + '
        "'"   → Returns: current stock (1,850 units), days supply (13.0), incoming (2,300 units)"'",' + '
        "'""'",' + '
        "'"2. Analyze health indicators and identify issues"'",' + '
        "'"   → Check if stock < safety_stock (NO: 1,850 > 300)"'",' + '
        "'"   → Check days of supply (13.0 days = adequate)"'",' + '
        "'"   → Review stockout history (3 events, $111k lost)"'",' + '
        "'""'",' + '
        "'"3. Get demand forecast from Demand Intelligence Agent"'",' + '
        "'"   → Weekly demand forecast: 1,050 units (±120 std dev)"'",' + '
        "'"   → Daily demand: 150 units (1,050 / 7)"'",' + '
        "'""'",' + '
        "'"4. Call calculate_reorder_point() to determine when to order"'",' + '
        "'"   → Input: daily_demand=150, std_dev=21.4, lead_time=5, service_level=95%"'",' + '
        "'"   → Output: ROP = 961 units"'",' + '
        "'"   → Decision: Current stock (1,850) > ROP (961) → No immediate reorder"'",' + '
        "'""'",' + '
        "'"5. Call optimize_safety_stock() to evaluate current setting"'",' + '
        "'"   → Test service levels: 85%, 90%, 95%, 97%, 99%"'",' + '
        "'"   → Current: 300 units (~95% service level)"'",' + '
        "'"   → Optimal: 355 units (99% service level, $1,190 annual savings)"'",' + '
        "'"   → Recommendation: Increase safety stock to 355 units"'",' + '
        "'""'",' + '
        "'"6. Call simulate_stockout_risk() to quantify near-term risk"'",' + '
        "'"   → Run 1,000 Monte Carlo simulations over 14 days"'",' + '
        "'"   → Result: 2.3% overall stockout probability"'",' + '
        "'"   → Critical day: Day 14 with 636 units minimum"'",' + '
        "'"   → Decision: Risk acceptable, no emergency order needed"'",' + '
        "'""'",' + '
        "'"7. Call evaluate_holding_costs() for economic analysis"'",' + '
        "'"   → Current holding cost: $4,275/year"'",' + '
        "'"   → EOQ: 2,600 units (order every 18 days)"'",' + '
        "'"   → Capital tied up: $96,200"'",' + '
        "'"   → Historical stockout cost: $111,875 total"'",' + '
        "'""'",' + '
        "'"8. Call generate_replenishment_plan() to create action plan"'",' + '
        "'"   → 4-week planning horizon"'",' + '
        "'"   → Orders triggered in Week 3 and Week 4"'",' + '
        "'"   → Total orders: 4,000 units, $204,500 cost"'",' + '
        "'"   → Split: 65% SUP-A (reliable), 35% SUP-B (cheaper)"'",' + '
        "'""'",' + '
        "'"9. Present comprehensive recommendation to user"'",' + '
        "'"   → Summary of findings"'",' + '
        "'"   → Specific action items with timing"'",' + '
        "'"   → Cost-benefit analysis"'",' + '
        "'"   → Risk assessment"'",' + '
    ]' + '
' + '
    for step in flow:' + '
        if step == "'""'":' + '
            doc.add_paragraph()' + '
        else:' + '
            p = doc.add_paragraph(step)' + '
            if step[0].isdigit():' + '
                p.runs[0].bold = True' + '
            else:' + '
                p.style = "'"List Bullet"'"' + '
' + '
    # ===================================================================' + '
    # SECTION 10: SQL VALIDATION QUERIES' + '
    # ===================================================================' + '
    doc.add_page_break()' + '
    add_heading(doc, "'"10. SQL VALIDATION QUERIES"'", level=1)' + '
' + '
    doc.add_paragraph(' + '
        "'"Use these SQL queries to validate AI inputs and outputs at each step:"'"' + '
    )' + '
' + '
    add_heading(doc, "'"10.1 Validate Current Inventory Status"'", level=2)' + '
    val1 = doc.add_paragraph(' + '
        "'"SELECT i.product_id, i.current_stock, i.safety_stock, i.avg_daily_usage,\\n"'"' + '
        "'"       i.lead_time, i.stockout_risk, i.unit_cost, i.holding_cost,\\n"'"' + '
        "'"       ROUND(i.current_stock / i.avg_daily_usage, 1) as days_of_supply,\\n"'"' + '
        "'"       (SELECT COUNT(*) FROM purchase_orders po\\n"'"' + '
        "'"        WHERE po.product_id = i.product_id\\n"'"' + '
        "'"          AND po.status IN (\\"'"open\\"'", \\"'"in_transit\\"'", \\"'"processing\\"'")) as open_orders,\\n"'"' + '
        "'"       (SELECT SUM(po.quantity) FROM purchase_orders po\\n"'"' + '
        "'"        WHERE po.product_id = i.product_id\\n"'"' + '
        "'"          AND po.status IN (\\"'"open\\"'", \\"'"in_transit\\"'", \\"'"processing\\"'")) as incoming_units\\n"'"' + '
        "'"FROM inventory i\\n"'"' + '
        "'"WHERE i.product_id = \\"'"PROD-A\\"'";"'"' + '
    )' + '
    val1.runs[0].font.name = "'"Courier New"'"' + '
    val1.runs[0].font.size = Pt(8)' + '
' + '
    add_heading(doc, "'"10.2 Validate Reorder Point Calculation"'", level=2)' + '
    val2 = doc.add_paragraph(' + '
        "'"SELECT i.product_id,\\n"'"' + '
        "'"       i.avg_daily_usage,\\n"'"' + '
        "'"       i.lead_time,\\n"'"' + '
        "'"       i.safety_stock,\\n"'"' + '
        "'"       (i.avg_daily_usage * i.lead_time) as avg_demand_during_lt,\\n"'"' + '
        "'"       (i.avg_daily_usage * i.lead_time + i.safety_stock) as calculated_rop,\\n"'"' + '
        "'"       i.current_stock,\\n"'"' + '
        "'"       CASE WHEN i.current_stock < (i.avg_daily_usage * i.lead_time + i.safety_stock)\\n"'"' + '
        "'"            THEN \\"'"REORDER NOW\\"'"\\n"'"' + '
        "'"            ELSE \\"'"Stock OK\\"'"\\n"'"' + '
        "'"       END as reorder_recommendation\\n"'"' + '
        "'"FROM inventory i\\n"'"' + '
        "'"WHERE i.product_id = \\"'"PROD-A\\"'";"'"' + '
    )' + '
    val2.runs[0].font.name = "'"Courier New"'"' + '
    val2.runs[0].font.size = Pt(8)' + '
' + '
    add_heading(doc, "'"10.3 Validate Warehouse Utilization"'", level=2)' + '
    val3 = doc.add_paragraph(' + '
        "'"SELECT w.product_id,\\n"'"' + '
        "'"       w.zone_id,\\n"'"' + '
        "'"       w.capacity,\\n"'"' + '
        "'"       w.current_units,\\n"'"' + '
        "'"       w.utilization as utilization_pct,\\n"'"' + '
        "'"       w.zone_type,\\n"'"' + '
        "'"       w.temperature_controlled\\n"'"' + '
        "'"FROM warehouse_zones w\\n"'"' + '
        "'"WHERE w.product_id = \\"'"PROD-A\\"'"\\n"'"' + '
        "'"UNION ALL\\n"'"' + '
        "'"SELECT \\"'"TOTAL\\"'" as product_id,\\n"'"' + '
        "'"       \\"'"ALL\\"'" as zone_id,\\n"'"' + '
        "'"       SUM(w.capacity) as capacity,\\n"'"' + '
        "'"       SUM(w.current_units) as current_units,\\n"'"' + '
        "'"       ROUND((SUM(w.current_units) * 100.0 / SUM(w.capacity)), 1) as utilization_pct,\\n"'"' + '
        "'"       \\"'"--\\"'" as zone_type,\\n"'"' + '
        "'"       0 as temperature_controlled\\n"'"' + '
        "'"FROM warehouse_zones w\\n"'"' + '
        "'"WHERE w.product_id = \\"'"PROD-A\\"'";"'"' + '
    )' + '
    val3.runs[0].font.name = "'"Courier New"'"' + '
    val3.runs[0].font.size = Pt(8)' + '
' + '
    add_heading(doc, "'"10.4 Validate Stockout History"'", level=2)' + '
    val4 = doc.add_paragraph(' + '
        "'"SELECT s.product_id,\\n"'"' + '
        "'"       COUNT(*) as total_events,\\n"'"' + '
        "'"       SUM(s.duration_days) as total_days,\\n"'"' + '
        "'"       AVG(s.duration_days) as avg_duration_days,\\n"'"' + '
        "'"       SUM(s.units_short) as total_units_short,\\n"'"' + '
        "'"       SUM(s.revenue_lost) as total_revenue_lost,\\n"'"' + '
        "'"       AVG(s.revenue_lost) as avg_revenue_per_event,\\n"'"' + '
        "'"       SUM(s.customers_affected) as total_customers_affected\\n"'"' + '
        "'"FROM stockout_events s\\n"'"' + '
        "'"WHERE s.product_id = \\"'"PROD-A\\"'"\\n"'"' + '
        "'"GROUP BY s.product_id;"'"' + '
    )' + '
    val4.runs[0].font.name = "'"Courier New"'"' + '
    val4.runs[0].font.size = Pt(8)' + '
' + '
    add_heading(doc, "'"10.5 Validate Supplier Performance"'", level=2)' + '
    val5 = doc.add_paragraph(' + '
        "'"SELECT s.id, s.name, s.on_time_delivery, s.quality_score,\\n"'"' + '
        "'"       s.lead_time, s.lead_time_variability, s.base_cost,\\n"'"' + '
        "'"       COUNT(po.po_id) as total_orders,\\n"'"' + '
        "'"       SUM(po.quantity) as total_units_ordered,\\n"'"' + '
        "'"       AVG(julianday(po.actual_delivery_date) - julianday(po.order_date)) as avg_actual_lead_time\\n"'"' + '
        "'"FROM suppliers s\\n"'"' + '
        "'"LEFT JOIN purchase_orders po ON s.id = po.supplier_id\\n"'"' + '
        "'"     AND po.product_id = \\"'"PROD-A\\"'"\\n"'"' + '
        "'"     AND po.status = \\"'"delivered\\"'"\\n"'"' + '
        "'"GROUP BY s.id;"'"' + '
    )' + '
    val5.runs[0].font.name = "'"Courier New"'"' + '
    val5.runs[0].font.size = Pt(8)' + '
' + '
    # ===================================================================' + '
    # SECTION 11: FORMULA REFERENCE' + '
    # ===================================================================' + '
    doc.add_page_break()' + '
    add_heading(doc, "'"11. FORMULA REFERENCE SHEET"'", level=1)' + '
' + '
    formulas = [' + '
        ["'"Formula"'", "'"Equation"'", "'"Purpose"'"],' + '
        ["'"Reorder Point (ROP)"'", "'"ROP = (avg_daily_demand × lead_time) + safety_stock"'", "'"When to order"'"],' + '
        ["'"Safety Stock"'", "'"SS = Z × √(LT × σ_demand² + demand² × σ_LT²)"'", "'"Buffer against uncertainty"'"],' + '
        ["'"EOQ"'", "'"EOQ = √(2 × annual_demand × ordering_cost / holding_cost)"'", "'"Optimal order size"'"],' + '
        ["'"Days of Supply"'", "'"DoS = current_stock / avg_daily_demand"'", "'"How long stock lasts"'"],' + '
        ["'"Holding Cost"'", "'"HC = stock_level × cost_per_unit_per_year"'", "'"Cost to carry inventory"'"],' + '
        ["'"Stockout Probability"'", "'"P(stockout) = simulations with stockout / total simulations"'", "'"Risk quantification"'"],' + '
        ["'"Warehouse Utilization"'", "'"Util% = (current_units / capacity) × 100"'", "'"Space usage"'"],' + '
        ["'"Service Level"'", "'"SL = 1 - stockout_probability"'", "'"Fill rate target"'"],' + '
    ]' + '
    add_table_data(doc, formulas[0], formulas[1:])' + '
' + '
    add_heading(doc, "'"Z-Score Reference"'", level=2)' + '
    z_ref = [' + '
        ["'"Service Level"'", "'"Z-Score"'", "'"Interpretation"'"],' + '
        ["'"85%"'", "'"1.04"'", "'"15 out of 100 orders may stockout"'"],' + '
        ["'"90%"'", "'"1.28"'", "'"10 out of 100 orders may stockout"'"],' + '
        ["'"95%"'", "'"1.645"'", "'"5 out of 100 orders may stockout (industry standard)"'"],' + '
        ["'"97%"'", "'"1.88"'", "'"3 out of 100 orders may stockout"'"],' + '
        ["'"99%"'", "'"2.326"'", "'"1 out of 100 orders may stockout (premium service)"'"],' + '
    ]' + '
    add_table_data(doc, z_ref[0], z_ref[1:])' + '
' + '
    # ===================================================================' + '
    # SECTION 12: SUMMARY' + '
    # ===================================================================' + '
    doc.add_page_break()' + '
    add_heading(doc, "'"12. SUMMARY"'", level=1)' + '
' + '
    doc.add_paragraph("'"The Inventory Management Agent provides:"'").bold = True' + '
    doc.add_paragraph()' + '
' + '
    summary_points = [' + '
        "'"✓ 6 sophisticated tools covering all aspects of inventory management"'",' + '
        "'"✓ Real-time queries across 12 database tables with 281 records"'",' + '
        "'"✓ Advanced algorithms: ROP, EOQ, Safety Stock Optimization, Monte Carlo"'",' + '
        "'"✓ Multi-supplier allocation strategy (65%/35% split)"'",' + '
        "'"✓ Complete cost analysis: holding costs, stockout costs, capital tied up"'",' + '
        "'"✓ Risk quantification with 1,000-run Monte Carlo simulations"'",' + '
        "'"✓ 4-week replenishment planning with specific order recommendations"'",' + '
        "'"✓ SQL validation queries for every calculation"'",' + '
        "'"✓ 100% database-driven (no hardcoded data)"'",' + '
    ]' + '
    for point in summary_points:' + '
        doc.add_paragraph(point, style="'"List Bullet"'")' + '
' + '
    doc.add_paragraph()' + '
    doc.add_paragraph("'"Key Metrics Tracked:"'").bold = True' + '
    metrics = [' + '
        "'"Current Stock: 1,850 units"'",' + '
        "'"Safety Stock: 300 units (recommended: 355 units)"'",' + '
        "'"Days of Supply: 13.0 days"'",' + '
        "'"Reorder Point: 961 units"'",' + '
        "'"Economic Order Quantity: 2,600 units"'",' + '
        "'"Warehouse Utilization: 37.0%"'",' + '
        "'"Incoming Pipeline: 2,300 units"'",' + '
        "'"Stockout Risk (14-day): 2.3%"'",' + '
        "'"Annual Holding Cost: $4,275"'",' + '
        "'"Historical Stockout Cost: $111,875"'",' + '
    ]' + '
    for metric in metrics:' + '
        doc.add_paragraph(metric, style="'"List Bullet"'")' + '
' + '
    doc.add_paragraph()' + '
    doc.add_paragraph("'"Database Tables Used:"'").bold = True' + '
    tables_summary = [' + '
        "'"inventory (1 record) - stock levels, costs"'",' + '
        "'"warehouse_zones (3 records) - zone allocation"'",' + '
        "'"purchase_orders (12 records) - order history"'",' + '
        "'"stockout_events (3 records) - historical stockouts"'",' + '
        "'"suppliers (2 records) - supplier data"'",' + '
        "'"products, bom_items, supplier_contracts, supplier_risk, historical_demand_data, market_context_data, production_lines"'",' + '
    ]' + '
    for table in tables_summary:' + '
        doc.add_paragraph(table, style="'"List Bullet"'")' + '
' + '
    # Footer' + '
    doc.add_paragraph()' + '
    doc.add_paragraph()' + '
    footer = doc.add_paragraph("'"─"'" * 80)' + '
    footer.alignment = WD_PARAGRAPH_ALIGNMENT.CENTER' + '
    end_note = doc.add_paragraph("'"END OF INVENTORY MANAGEMENT COMPLETE GUIDE"'")' + '
    end_note.alignment = WD_PARAGRAPH_ALIGNMENT.CENTER' + '
    end_note.runs[0].font.size = Pt(10)' + '
    end_note.runs[0].italic = True' + '
' + '
    # Save' + '
    doc.save("'"INVENTORY_MANAGEMENT_COMPLETE_GUIDE_UPDATED.docx"'")' + '
    print("'"Document created successfully!"'")' + '
    print("'"File: INVENTORY_MANAGEMENT_COMPLETE_GUIDE_UPDATED.docx"'")' + '
    print("'"Sections: 12 comprehensive sections covering all 6 tools"'")' + '
    print("'"Pages: ~35 pages with tables, formulas, SQL queries, and examples"'")' + '
' + '
if __name__ == "'"__main__"'":' + '
    create_inventory_guide()' + '
