"""
Complete Word Document with SQL Validation Queries
Shows EXACTLY which tables/columns are used and how to validate
"""
from docx import Document
from docx.shared import Inches, Pt, RGBColor
from docx.enum.text import WD_ALIGN_PARAGRAPH

def create_sql_validation_doc():
    doc = Document()

    style = doc.styles['Normal']
    font = style.font
    font.name = 'Calibri'
    font.size = Pt(11)

    # Title Page
    title = doc.add_heading('DEMAND INTELLIGENCE - DATA SOURCES & SQL VALIDATION', 0)
    title.alignment = WD_ALIGN_PARAGRAPH.CENTER

    subtitle = doc.add_paragraph('Complete Table & Column Reference with Validation Queries')
    subtitle.alignment = WD_ALIGN_PARAGRAPH.CENTER
    subtitle.runs[0].font.size = Pt(14)
    subtitle.runs[0].font.bold = True

    doc.add_paragraph()

    info = doc.add_paragraph()
    info.alignment = WD_ALIGN_PARAGRAPH.CENTER
    info.add_run('AMIS - Autonomous Manufacturing Intelligence System\n').font.size = Pt(11)
    info.add_run('Learn How to Validate AI Results with SQL').font.size = Pt(11)

    doc.add_page_break()

    # ================================================================
    # CRITICAL UNDERSTANDING: DATA SOURCES
    # ================================================================
    doc.add_heading('CRITICAL UNDERSTANDING: Where Data Comes From', 1)

    p = doc.add_paragraph()
    p.add_run('IMPORTANT: ').bold = True
    p.add_run('The Demand Forecasting Agent uses TWO types of data sources:')

    doc.add_heading('1. SIMULATED DATA (Python Functions) - AI TRAINING DATA', 2)

    p = doc.add_paragraph(
        'When the AI agent analyzes demand, it uses SIMULATED historical data generated by Python functions '
        'in sample_data.py. This mimics what would come from a real ERP/MES system in production.'
    )

    doc.add_paragraph()
    p = doc.add_paragraph()
    p.add_run('Location: ').bold = True
    p.add_run('data/sample_data.py')

    p = doc.add_paragraph()
    p.add_run('Why Simulated? ').bold = True
    p.add_run('For the hackathon demo, we generate realistic historical data on-the-fly instead of loading from a real ERP database.')

    table1 = doc.add_table(rows=6, cols=3)
    table1.style = 'Light Grid Accent 1'

    hdr = table1.rows[0].cells
    hdr[0].text = 'Tool Calls Function'
    hdr[1].text = 'Data Type'
    hdr[2].text = 'NOT FROM DATABASE'
    for cell in hdr:
        for para in cell.paragraphs:
            for run in para.runs:
                run.font.bold = True

    funcs = [
        ('get_historical_demand()', 'Past 12 weeks of demand data', 'Generated by Python algorithm'),
        ('get_current_inventory()', 'Current stock levels', 'Hardcoded values in Python'),
        ('get_market_context()', 'External market factors', 'Hardcoded values in Python'),
        ('get_production_capacity()', 'Machine capacity', 'Hardcoded values in Python'),
        ('get_product_info()', 'Product details', 'Hardcoded values in Python'),
    ]

    for i, (func, data_type, source) in enumerate(funcs, start=1):
        row = table1.rows[i].cells
        row[0].text = func
        row[1].text = data_type
        row[2].text = source

    doc.add_paragraph()

    alert = doc.add_paragraph()
    alert_run = alert.add_run('⚠️ YOU CANNOT QUERY THESE WITH SQL - They are Python functions, not database tables!')
    alert_run.font.bold = True
    alert_run.font.color.rgb = RGBColor(255, 0, 0)

    doc.add_page_break()

    doc.add_heading('2. DATABASE TABLES - AI RESULTS STORAGE', 2)

    p = doc.add_paragraph(
        'After the AI agent generates forecasts, the RESULTS are stored in SQLite database tables. '
        'These you CAN query with SQL to validate.'
    )

    doc.add_paragraph()
    p = doc.add_paragraph()
    p.add_run('Location: ').bold = True
    p.add_run('backend/amis.db (SQLite database file)')

    table2 = doc.add_table(rows=4, cols=3)
    table2.style = 'Light Grid Accent 1'

    hdr2 = table2.rows[0].cells
    hdr2[0].text = 'Table Name'
    hdr2[1].text = 'What It Stores'
    hdr2[2].text = 'Can Query with SQL?'
    for cell in hdr2:
        for para in cell.paragraphs:
            for run in para.runs:
                run.font.bold = True

    tables = [
        ('demand_forecasts', 'AI-generated forecasts (optimistic, base, pessimistic)', '✅ YES - Use SQL below'),
        ('products', 'Product master data', '✅ YES - Use SQL below'),
        ('inventory', 'Current inventory status', '✅ YES - Use SQL below'),
    ]

    for i, (table, stores, can_query) in enumerate(tables, start=1):
        row = table2.rows[i].cells
        row[0].text = table
        row[1].text = stores
        row[2].text = can_query

    doc.add_page_break()

    # ================================================================
    # TOOL 1: DETAILED DATA SOURCE MAPPING
    # ================================================================
    doc.add_heading('TOOL 1: get_demand_data_summary() - DATA SOURCES', 1)

    doc.add_heading('What This Tool Does', 2)
    p = doc.add_paragraph('Gathers all context data by calling 5 Python functions.')

    doc.add_heading('Data Source Breakdown', 2)

    # Function 1
    p = doc.add_paragraph()
    p.add_run('Function 1: get_historical_demand(product_id, weeks=12)').bold = True

    p = doc.add_paragraph()
    p.add_run('Source: ').bold = True
    p.add_run('Python function in data/sample_data.py (lines 11-58)')

    p = doc.add_paragraph()
    p.add_run('Algorithm: ').bold = True
    p.add_run('Generates 12 weeks of simulated demand using formula:')

    code1 = """demand = base_demand + trend_value + seasonal + noise + anomaly

Where:
  base_demand = 950 units
  trend_value = 15 * (weeks - i)  [linear growth]
  seasonal = 120 * sin(2π * week_num / 52)  [annual seasonality]
  noise = random.gauss(0, 60)  [random variation]
  anomaly = 380 if week 3 else 0  [promotional spike]"""

    p = doc.add_paragraph(code1)
    for run in p.runs:
        run.font.name = 'Courier New'
        run.font.size = Pt(9)

    p = doc.add_paragraph()
    p.add_run('Output Columns: ').bold = True

    table3 = doc.add_table(rows=7, cols=3)
    table3.style = 'Light Grid Accent 1'

    hdr3 = table3.rows[0].cells
    hdr3[0].text = 'Column'
    hdr3[1].text = 'Type'
    hdr3[2].text = 'Example Value'
    for cell in hdr3:
        for para in cell.paragraphs:
            for run in para.runs:
                run.font.bold = True

    cols = [
        ('week', 'string', '"2026-W10"'),
        ('date', 'string', '"2026-03-09"'),
        ('product_id', 'string', '"PROD-A"'),
        ('demand_units', 'integer', '1107'),
        ('anomaly', 'boolean', 'false'),
        ('avg_price', 'float', '88.50'),
    ]

    for i, (col, typ, example) in enumerate(cols, start=1):
        row = table3.rows[i].cells
        row[0].text = col
        row[1].text = typ
        row[2].text = example

    doc.add_paragraph()
    alert2 = doc.add_paragraph()
    alert2_run = alert2.add_run('❌ CANNOT VALIDATE WITH SQL - This is generated data, not stored in database')
    alert2_run.font.bold = True
    alert2_run.font.color.rgb = RGBColor(255, 0, 0)

    doc.add_paragraph()
    p = doc.add_paragraph()
    p.add_run('How to Verify: ').bold = True
    p.add_run('Run the Python function directly in Python shell:')

    verify1 = """# In Python:
from data.sample_data import get_historical_demand

historical = get_historical_demand("PROD-A", 12)
print(f"Generated {len(historical)} weeks of data")
print(f"Week 1 demand: {historical[0]['demand_units']} units")
print(f"Week 12 demand: {historical[-1]['demand_units']} units")

# Expected output:
# Generated 12 weeks of data
# Week 1 demand: 1107 units  (will vary due to random noise)
# Week 12 demand: 1240 units"""

    p = doc.add_paragraph(verify1)
    for run in p.runs:
        run.font.name = 'Courier New'
        run.font.size = Pt(8)
        run.font.color.rgb = RGBColor(0, 100, 0)

    doc.add_page_break()

    # Function 2
    p = doc.add_paragraph()
    p.add_run('Function 2: get_current_inventory(product_id)').bold = True

    p = doc.add_paragraph()
    p.add_run('Source: ').bold = True
    p.add_run('Python function in data/sample_data.py (lines 61-77) - Returns hardcoded dict')

    p = doc.add_paragraph()
    p.add_run('ALTERNATIVE: Can also query database inventory table').bold = True

    sql1 = """-- Query database for REAL inventory (if populated):
SELECT
    product_id,
    current_stock,
    safety_stock,
    avg_daily_usage,
    stockout_risk
FROM inventory
WHERE product_id = 'PROD-A';

-- Expected result (if database has data):
-- product_id | current_stock | safety_stock | avg_daily_usage | stockout_risk
-- PROD-A     | 1850          | 300          | 142             | 0.15"""

    p = doc.add_paragraph(sql1)
    for run in p.runs:
        run.font.name = 'Courier New'
        run.font.size = Pt(9)
        run.font.color.rgb = RGBColor(0, 0, 128)

    p = doc.add_paragraph()
    p.add_run('Database Table: ').bold = True
    p.add_run('inventory')

    p = doc.add_paragraph()
    p.add_run('Columns Used: ').bold = True

    table4 = doc.add_table(rows=6, cols=3)
    table4.style = 'Light Grid Accent 1'

    hdr4 = table4.rows[0].cells
    hdr4[0].text = 'Column'
    hdr4[1].text = 'Type'
    hdr4[2].text = 'Business Meaning'
    for cell in hdr4:
        for para in cell.paragraphs:
            for run in para.runs:
                run.font.bold = True

    inv_cols = [
        ('product_id', 'TEXT', 'Which product'),
        ('current_stock', 'INTEGER', 'Units in warehouse right now'),
        ('safety_stock', 'INTEGER', 'Minimum buffer to avoid stockouts'),
        ('avg_daily_usage', 'REAL', 'How many units consumed per day'),
        ('stockout_risk', 'REAL', 'Probability of running out (0-1)'),
    ]

    for i, (col, typ, meaning) in enumerate(inv_cols, start=1):
        row = table4.rows[i].cells
        row[0].text = col
        row[1].text = typ
        row[2].text = meaning

    doc.add_page_break()

    # ================================================================
    # TOOL 2: SIMULATE DEMAND SCENARIOS - VALIDATION
    # ================================================================
    doc.add_heading('TOOL 2: simulate_demand_scenarios() - RESULTS VALIDATION', 1)

    doc.add_heading('What This Tool Does', 2)
    p = doc.add_paragraph('Generates 3 forecast scenarios and stores them in demand_forecasts table.')

    doc.add_heading('Input: Simulated Historical Data', 2)
    p = doc.add_paragraph('Uses output from get_historical_demand() - cannot query with SQL')

    doc.add_heading('Output: Database Storage', 2)
    p = doc.add_paragraph()
    p.add_run('Table: ').bold = True
    p.add_run('demand_forecasts')

    p = doc.add_paragraph()
    p.add_run('Location: ').bold = True
    p.add_run('backend/amis.db')

    doc.add_heading('Table Schema', 2)

    table5 = doc.add_table(rows=10, cols=4)
    table5.style = 'Light Grid Accent 1'

    hdr5 = table5.rows[0].cells
    hdr5[0].text = 'Column'
    hdr5[1].text = 'Type'
    hdr5[2].text = 'Nullable'
    hdr5[3].text = 'What Tool Writes Here'
    for cell in hdr5:
        for para in cell.paragraphs:
            for run in para.runs:
                run.font.bold = True

    forecast_schema = [
        ('id', 'INTEGER', 'NO', 'Auto-increment'),
        ('product_id', 'TEXT', 'NO', 'From pipeline ("PROD-A")'),
        ('week_number', 'INTEGER', 'YES', 'Calculated (current week + 1, 2, 3, 4)'),
        ('forecast_date', 'DATE', 'YES', 'Start date of forecast week'),
        ('optimistic', 'INTEGER', 'YES', 'Tool 2 output: optimistic scenario'),
        ('base_case', 'INTEGER', 'YES', 'Tool 2 output: base scenario'),
        ('pessimistic', 'INTEGER', 'YES', 'Tool 2 output: pessimistic scenario'),
        ('actual', 'INTEGER', 'YES', 'NULL initially, filled by user later'),
        ('created_at', 'TIMESTAMP', 'NO', 'Auto timestamp'),
    ]

    for i, (col, typ, null, writes) in enumerate(forecast_schema, start=1):
        row = table5.rows[i].cells
        row[0].text = col
        row[1].text = typ
        row[2].text = null
        row[3].text = writes

    doc.add_page_break()

    doc.add_heading('SQL VALIDATION QUERIES', 2)

    p = doc.add_paragraph()
    p.add_run('Query 1: Check if forecasts exist for a product').bold = True

    query1 = """SELECT COUNT(*) as forecast_count
FROM demand_forecasts
WHERE product_id = 'PROD-A';

-- Expected: 4, 8, or 12 (depending on how many times pipeline ran)
-- If 0: Pipeline has not been run yet"""

    p = doc.add_paragraph(query1)
    for run in p.runs:
        run.font.name = 'Courier New'
        run.font.size = Pt(9)
        run.font.color.rgb = RGBColor(0, 0, 128)

    doc.add_paragraph()
    p = doc.add_paragraph()
    p.add_run('Query 2: View all forecasts with validation').bold = True

    query2 = """SELECT
    week_number,
    forecast_date,
    optimistic,
    base_case,
    pessimistic,
    actual,
    CASE
        WHEN optimistic >= base_case AND base_case >= pessimistic THEN 'VALID'
        ELSE 'INVALID - Data Quality Issue'
    END as validation_status
FROM demand_forecasts
WHERE product_id = 'PROD-A'
ORDER BY week_number;

-- Expected:
-- All rows should have validation_status = 'VALID'
-- optimistic should be highest, pessimistic lowest"""

    p = doc.add_paragraph(query2)
    for run in p.runs:
        run.font.name = 'Courier New'
        run.font.size = Pt(9)
        run.font.color.rgb = RGBColor(0, 0, 128)

    doc.add_paragraph()
    p = doc.add_paragraph()
    p.add_run('Query 3: Calculate average forecast (should match UI)').bold = True

    query3 = """SELECT
    AVG(base_case) as avg_base_forecast,
    MIN(base_case) as min_forecast,
    MAX(base_case) as max_forecast,
    COUNT(*) as weeks_forecasted
FROM demand_forecasts
WHERE product_id = 'PROD-A';

-- Compare to UI:
-- avg_base_forecast should match "Average Weekly Demand" metric card
-- Example: 1088 units"""

    p = doc.add_paragraph(query3)
    for run in p.runs:
        run.font.name = 'Courier New'
        run.font.size = Pt(9)
        run.font.color.rgb = RGBColor(0, 0, 128)

    doc.add_paragraph()
    p = doc.add_paragraph()
    p.add_run('Query 4: Calculate trend slope (should match UI)').bold = True

    query4 = """WITH ordered_forecasts AS (
    SELECT
        base_case,
        week_number,
        ROW_NUMBER() OVER (ORDER BY week_number) as row_num
    FROM demand_forecasts
    WHERE product_id = 'PROD-A'
)
SELECT
    (SELECT base_case FROM ordered_forecasts WHERE row_num = 1) as first_week,
    (SELECT base_case FROM ordered_forecasts ORDER BY row_num DESC LIMIT 1) as last_week,
    COUNT(*) as total_weeks,
    ((SELECT base_case FROM ordered_forecasts ORDER BY row_num DESC LIMIT 1) -
     (SELECT base_case FROM ordered_forecasts WHERE row_num = 1)) * 1.0 /
     COUNT(*) as trend_slope
FROM ordered_forecasts;

-- Compare to UI:
-- trend_slope should match trend calculation
-- Example: 18.75 units/week = Upward trend"""

    p = doc.add_paragraph(query4)
    for run in p.runs:
        run.font.name = 'Courier New'
        run.font.size = Pt(9)
        run.font.color.rgb = RGBColor(0, 0, 128)

    doc.add_page_break()

    # ================================================================
    # COMPLETE DATA FLOW DIAGRAM
    # ================================================================
    doc.add_heading('COMPLETE DATA FLOW: Python Functions → Tools → Database → UI', 1)

    flow = """
┌─────────────────────────────────────────────────────────────┐
│  STEP 1: PYTHON FUNCTIONS (Simulated Data)                 │
│  Location: data/sample_data.py                              │
└─────────────────────────────────────────────────────────────┘
                         ↓
    get_historical_demand()  →  Returns: 12 weeks of demand data
    get_current_inventory()  →  Returns: Stock levels
    get_market_context()     →  Returns: External factors
    get_production_capacity()→  Returns: Capacity data
                         ↓
┌─────────────────────────────────────────────────────────────┐
│  STEP 2: TOOL 1 (get_demand_data_summary)                  │
│  Combines all Python function outputs into one JSON        │
└─────────────────────────────────────────────────────────────┘
                         ↓
┌─────────────────────────────────────────────────────────────┐
│  STEP 3: TOOL 2 (simulate_demand_scenarios)                │
│  Uses historical data to calculate:                         │
│  - Optimistic scenario (1391, 1427, 1464, 1500 units)      │
│  - Base scenario (1210, 1222, 1234, 1246 units)            │
│  - Pessimistic scenario (992, 968, 943, 919 units)         │
└─────────────────────────────────────────────────────────────┘
                         ↓
┌─────────────────────────────────────────────────────────────┐
│  STEP 4: DATABASE WRITE (ai_database_bridge.py)            │
│  Inserts 4 rows into demand_forecasts table:               │
│                                                              │
│  INSERT INTO demand_forecasts (                             │
│    product_id, week_number, forecast_date,                 │
│    optimistic, base_case, pessimistic                       │
│  ) VALUES                                                    │
│    ('PROD-A', 11, '2026-03-16', 1391, 1210, 992),          │
│    ('PROD-A', 12, '2026-03-23', 1427, 1222, 968),          │
│    ('PROD-A', 13, '2026-03-30', 1464, 1234, 943),          │
│    ('PROD-A', 14, '2026-04-06', 1500, 1246, 919);          │
└─────────────────────────────────────────────────────────────┘
                         ↓
┌─────────────────────────────────────────────────────────────┐
│  STEP 5: DATABASE STORAGE (backend/amis.db)                │
│  Table: demand_forecasts                                    │
│  ✅ NOW YOU CAN QUERY WITH SQL                              │
└─────────────────────────────────────────────────────────────┘
                         ↓
┌─────────────────────────────────────────────────────────────┐
│  STEP 6: API ENDPOINT (main.py)                             │
│  GET /api/demand/forecasts/PROD-A                           │
│                                                              │
│  SELECT * FROM demand_forecasts                             │
│  WHERE product_id = 'PROD-A'                                │
│  ORDER BY week_number                                        │
└─────────────────────────────────────────────────────────────┘
                         ↓
┌─────────────────────────────────────────────────────────────┐
│  STEP 7: FRONTEND (DemandIntelligence.jsx)                 │
│  Receives JSON, calculates:                                 │
│  - avgBase = sum(base_case) / count                        │
│  - trend = (last - first) / count                          │
│  Displays in UI charts and metric cards                     │
└─────────────────────────────────────────────────────────────┘
"""

    p = doc.add_paragraph(flow)
    for run in p.runs:
        run.font.name = 'Courier New'
        run.font.size = Pt(8)

    doc.add_page_break()

    # ================================================================
    # VALIDATION WORKFLOW
    # ================================================================
    doc.add_heading('STEP-BY-STEP VALIDATION WORKFLOW', 1)

    doc.add_heading('Goal: Verify AI-Generated Forecasts Are Correct', 2)

    p = doc.add_paragraph()
    p.add_run('Step 1: Run the Pipeline').bold = True

    step1 = """# Start backend
cd backend
python main.py

# In another terminal, trigger pipeline via API
curl -X POST http://localhost:8000/api/pipeline/run \\
  -H "Content-Type: application/json" \\
  -d '{"product_id": "PROD-A"}'

# Wait 60 seconds for pipeline to complete"""

    p = doc.add_paragraph(step1)
    for run in p.runs:
        run.font.name = 'Courier New'
        run.font.size = Pt(9)

    doc.add_paragraph()
    p = doc.add_paragraph()
    p.add_run('Step 2: Connect to Database').bold = True

    step2 = """# Open SQLite database
cd backend
sqlite3 amis.db

# Or use a GUI tool:
# - DB Browser for SQLite (https://sqlitebrowser.org)
# - Open file: backend/amis.db"""

    p = doc.add_paragraph(step2)
    for run in p.runs:
        run.font.name = 'Courier New'
        run.font.size = Pt(9)

    doc.add_paragraph()
    p = doc.add_paragraph()
    p.add_run('Step 3: Run Validation Query').bold = True

    step3 = """SELECT * FROM demand_forecasts WHERE product_id = 'PROD-A';

-- You should see 4 rows (weeks 11, 12, 13, 14)
-- Check: optimistic > base_case > pessimistic for each row"""

    p = doc.add_paragraph(step3)
    for run in p.runs:
        run.font.name = 'Courier New'
        run.font.size = Pt(9)
        run.font.color.rgb = RGBColor(0, 0, 128)

    doc.add_paragraph()
    p = doc.add_paragraph()
    p.add_run('Step 4: Compare to UI').bold = True

    step4 = """# Open frontend
http://localhost:5173/demand-intelligence

# Check:
1. "Average Weekly Demand" should match AVG(base_case) from SQL
2. "Trend Direction" should match your trend calculation
3. Chart should show 4 forecast weeks"""

    p = doc.add_paragraph(step4)
    for run in p.runs:
        run.font.name = 'Courier New'
        run.font.size = Pt(9)

    doc.add_paragraph()
    p = doc.add_paragraph()
    p.add_run('Step 5: Manual Calculation Verification').bold = True

    step5 = """# Let's say SQL returns:
# Week 11: base_case = 1210
# Week 12: base_case = 1222
# Week 13: base_case = 1234
# Week 14: base_case = 1246

# Manual calculation:
avg = (1210 + 1222 + 1234 + 1246) / 4 = 4912 / 4 = 1228 units

# Check UI: Should show "1,228 units" in Average Weekly Demand card"""

    p = doc.add_paragraph(step5)
    for run in p.runs:
        run.font.name = 'Courier New'
        run.font.size = Pt(9)

    doc.add_page_break()

    # ================================================================
    # SUMMARY TABLE
    # ================================================================
    doc.add_heading('QUICK REFERENCE: What Can You Query?', 1)

    table6 = doc.add_table(rows=6, cols=4)
    table6.style = 'Light Grid Accent 1'

    hdr6 = table6.rows[0].cells
    hdr6[0].text = 'Data Source'
    hdr6[1].text = 'Can Query SQL?'
    hdr6[2].text = 'How to Access'
    hdr6[3].text = 'Used By'
    for cell in hdr6:
        for para in cell.paragraphs:
            for run in para.runs:
                run.font.bold = True

    summary = [
        ('Historical demand (12 weeks)', '❌ NO', 'Python: get_historical_demand()', 'Tool 2 for calculations'),
        ('Market context', '❌ NO', 'Python: get_market_context()', 'Tool 1 for context'),
        ('Production capacity', '❌ NO', 'Python: get_production_capacity()', 'Tool 1 for context'),
        ('AI forecast results', '✅ YES', 'SQL: SELECT * FROM demand_forecasts', 'UI charts, validation'),
        ('Product master data', '✅ YES', 'SQL: SELECT * FROM products', 'Product dropdown'),
    ]

    for i, (source, can_query, how, used_by) in enumerate(summary, start=1):
        row = table6.rows[i].cells
        row[0].text = source
        row[1].text = can_query
        row[2].text = how
        row[3].text = used_by

    doc.add_page_break()

    # Conclusion
    doc.add_heading('CONCLUSION', 1)

    p = doc.add_paragraph()
    p.add_run('Key Takeaways:').bold = True

    doc.add_paragraph(
        '1. AI tools use SIMULATED data from Python functions (cannot query with SQL)',
        style='List Number'
    )
    doc.add_paragraph(
        '2. AI RESULTS are stored in demand_forecasts table (CAN query with SQL)',
        style='List Number'
    )
    doc.add_paragraph(
        '3. To validate: Run pipeline → Query database → Compare to UI',
        style='List Number'
    )
    doc.add_paragraph(
        '4. Use SQL queries provided in this document to verify correctness',
        style='List Number'
    )

    doc.add_paragraph()
    p = doc.add_paragraph()
    p.add_run('Now you can confidently validate every number the AI produces!').italic = True

    # Save
    output_path = 'DEMAND_INTELLIGENCE_SQL_VALIDATION.docx'
    doc.save(output_path)
    print(f"[OK] SQL Validation document created: {output_path}")
    return output_path

if __name__ == "__main__":
    create_sql_validation_doc()
